version: '3.8'

services:
  # Define the Product Service
  product-service:
    build: ./product_service
    ports:
      - "5001:5001"
    networks:
      - ecommerce-network

  # Define the Order Service
  order-service:
    build: ./order_service
    ports:
      - "5002:5002"
    networks:
      - ecommerce-network
    depends_on:
      - product-service

networks:
  ecommerce-network:
    driver: bridge