name: E-commerce CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python for test runner
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install test dependencies
        working-directory: ./tests
        run: pip install -r requirements.txt

      - name: Start all services with Docker Compose
        run: docker compose up --build -d

      - name: Wait for services to be healthy
        # In a real-world scenario, you might use a more sophisticated health check.
        # For our project, a generous sleep is reliable and simple.
        run: sleep 20

      - name: Run API and E2E tests
        working-directory: ./tests
        run: pytest test_api.py

      - name: Run Consumer contract test
        working-directory: ./tests
        run: pytest test_contract.py

      - name: Run Provider contract verification
        working-directory: ./tests
        run: |
          pact-verifier --provider-base-url=http://localhost:5001 \
                        --pact-url=./pacts/orderservice-productservice.json